### ISSUE TITLE
Did you mange to solve issue "Scrolling using trackpad while hovering link will opening that link in browser"? #1

### ISSUE THREAD

**Issue by igavrysh** [antoniomcr96/Thinkpad-L390-Yoga-macOS-Opencore#2]
Hi,

Thx for sharing EFI folder here!

I have Lenovo Thinkpad X1 Yoga Gen 3.

I tried many repos for my laptop, however the issue of auto click while scrolling with middle button + trackpoint persists.

e.g. whenever I scroll using Trackpoint - pointing finger on Trackpoint and thumb on middle button - every link, clickable image etc which falls under mouse pointer automatically opens (if I am using a browser).

Do you experience the same issue with your build? Did you mange to fix it?

**Comment by antoniomcr96** [comment]
Hi,
my trackpad is an ELAN trackpad and has worked well without the issue you explained since the [2.1.7](https://github.com/acidanthera/VoodooPS2/releases/tag/2.1.7) version of VoodooPS2 kext.
In another build on github for your laptop: https://github.com/KirisameR/ThinkPad-X1-Yoga-3rd-Hackintosh VoodooRMI is the kext used for the trackpad. If you have a Synaptic trackpad, this could be the issue. Try to use [VoodooRMI](https://github.com/VoodooSMBus/VoodooRMI). Otherwise I don't know, maybe it's a bug of VoodooPS2. In that case, you could report it to the acidanthera team

**Comment by antoniomcr96** [comment]
Closed due to inactivity. Feel free to reply if you have other questions
