### ISSUE TITLE
Touchscreen issue

### ISSUE THREAD

**Issue by achmadsy** [antoniomcr96/Thinkpad-L390-Yoga-macOS-Opencore#4]
Hi antonio, 1st, I would like to thanks for your work here.

I have Lenovo L390 non Yoga and all worked well expect for the touchscreen, mine ID are  RAYD0001 on the dsdt, are yours also the same? Can you help me to active mine on monterey, my issues are, the gpio detected and active, i2c controllers also actives, device also detected but crashed (on log) when reading device report from HIDFamily/VoodooI2CHID.

**Comment by antoniomcr96** [comment]
Hi, in this repository: https://github.com/digitalec/thinkmac-t470 @digitalec says that Raydium Touch systems aren't supported. Maybe it doesn't depend on i2c controllers but on the drivers for usb devices.
In fact, the touchscreen should be connected to the usb bus. For example, in my system i have a usb wacom touchscreen:
![image](https://user-images.githubusercontent.com/63928525/186380036-a81671a4-6a4b-4cae-997a-0df5f7ad6f5c.png)
Try to check on ioregistryexplorer if you have a device under hs06 usb port. If you have it, it is unsupported and i think that there's not a lot that can be done. Otherwise, maybe in your laptop the touchscreen is connected to another usb port (just an hypothesis) and you could try to remap your usb ports

**Comment by antoniomcr96** [comment]
Closed due to inactivity. If you have further questions, feel free to ask
